name: multirotas
description: multirotas.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.003
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.6
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_polyline_points: ^1.0.0
  dio: ^4.0.6
  firebase_database: ^9.0.7
  firebase_core: ^1.16.0
  cloud_firestore: ^3.1.14
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/carregamento.png
  - assets/mtMap.png
  - assets/busao.png
  - assets/paradaMap.png
  - assets/mapStyle.json
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launch.png"
