// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    messagingSenderId: '519420295610',
    projectId: 'multirotas-b3006',
    databaseURL: 'https://multirotas-b3006-default-rtdb.firebaseio.com',
    storageBucket: 'multirotas-b3006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    messagingSenderId: '519420295610',
    projectId: 'multirotas-b3006',
    databaseURL: 'https://multirotas-b3006-default-rtdb.firebaseio.com',
    storageBucket: 'multirotas-b3006.appspot.com',
    iosClientId:
        '519420295610-09c5jriksmsimc1t4q2rdcma48nkbne0.apps.googleusercontent.com',
    iosBundleId: 'com.example.multirotas',
  );
}
